### ISSUE TITLE
Could not find a way to edit wiki or contact someone

### ISSUE THREAD

**Issue by yene** [pilight/pilight#252]
Wiki says "Don't forget to tell us what protocol you used!" without further info how. Could not find a way to edit wiki or create an account.

I am using Intertechno IT-1500 with the kaku_switch protocol

**Comment by sRlinux** [comment]
The worst documentation i have ever seen! Not only because it is old, it is often wrong too...
So it is a lot of "reverse engineering" and read and understand bare C code! Why?

**Comment by pilino1234** [comment]
>The worst documentation i have ever seen!

Documentation of the functionality or of the actual pilight core? The functionality is documented in the manual (https://manual.pilight.org/) and the wiki (https://wiki.pilight.org/). The core is not documented anywhere, but it is not very big either. The directory structure and modularity makes it easy to find what you need. 
The forum is very active too, where you can ask for any help you need (https://forum.pilight.org/)
Both the manual and the wiki can be edit by anyone.

‌>old
‌>wrong
Hmm, could you elaborate on that a bit? Examples would be good too, so that they can be fixed.

>So it is a lot of "reverse engineering" and read and understand bare C code! Why?

What is "it"? Decoding the pulsetrains from the wireless devices is barely reverse engineering, it's more of a puzzle trying to find what the individual bits mean, but that can't be avoided. 
Since pilight is written in C, reading C code is quite necessary when working with it. C is used since it is fast and does not use a lot of resources on the target devices (over 60 of them).
The C code used here is fairly easy to understand; in fact I've been learning C from contributing to pilight. It is true that the code is not commented and documented all over the place, since it is often not really necessary.

**Comment by CurlyMoo** [comment]
> What is "it"? Decoding the pulsetrains from the wireless devices is barely reverse engineering, it's more of a puzzle trying to find what the individual bits mean, but that can't be avoided.

That's what reverse engineering means, so i should agree with him on this one 😄 

> The C code used here is fairly easy to understand; in fact I've been learning C from contributing to pilight. It is true that the code is not commented and documented all over the place, since it is often not really necessary.

Thanks for the complements. I do believe however that the structure of pilight is not very clear until now, but that is going to be fixed in de rewrite effort. The modularity does help, so you can find the place to add or fix something easily. That won't fix the issues linux guy has, because my efforts into working more with clearer `design patterns` only makes sense when you can recognize `design patterns` and know what they are.

For the rest i think someone didn't have a nice new years eve.
